export const libros = [
  // ROMANCE
  {
    titulo: "HeartStopper",
    autor: "Alice Oseman",
    genero: "Romance",
    descripcion: "Una novela gráfica tierna y honesta sobre el amor adolescente entre Charlie y Nick.",
    imagen: "/imagenes/PortadaHeartStopper.jpeg",
  },
  {
    titulo: "A través de mi ventana",
    autor: "Ariana Godoy",
    genero: "Romance",
    descripcion: "Raquel siempre estuvo enamorada de Ares, su enigmático vecino.",
    imagen: "/imagenes/PortadaVentana.jpeg",
  },
  {
    titulo: "Los dos mueren al final",
    autor: "Adam Silvera",
    genero: "Romance",
    descripcion: "Mateo y Rufus reciben la llamada: hoy es su último día.",
    imagen: "/imagenes/PortadaMueren.jpeg",
  },
  {
    titulo: "Antes de diciembre",
    autor: "Joana Marcus",
    genero: "Romance",
    descripcion: "Jenna conoce a su nuevo compañero de piso, cambiando su vida.",
    imagen: "/imagenes/PortadaDiciembre.jpeg",
  },
  {
    titulo: "Gente que conocemos en vacaciones",
    autor: "Emily Henry",
    genero: "Romance",
    descripcion: "Poppy y Alex tienen una última oportunidad para arreglarlo.",
    imagen: "/imagenes/PortadaVacaciones.jpeg",
  },
  {
    titulo: "Érase una vez un corazón roto",
    autor: "Stephanie Garber",
    genero: "Romance",
    descripcion: "Evangelina hace un trato con el Príncipe de los Corazones.",
    imagen: "/imagenes/PortadaRoto.jpeg",
  },

  // PSICOLOGÍA
  {
    titulo: "Psicopatología de la vida cotidiana",
    autor: "Sigmund Freud",
    genero: "Psicología",
    descripcion: "Los 'accidentes' diarios no son casuales, sino ventanas al inconsciente.",
    imagen: "/imagenes/PortadaCotidiana.gif",
  },
  {
    titulo: "El chiste y su relación con el inconsciente",
    autor: "Sigmund Freud",
    genero: "Psicología",
    descripcion: "Cómo los chistes expresan deseos reprimidos y conflictos internos.",
    imagen: "/imagenes/PortadaChiste.jpeg",
  },
  {
    titulo: "Los patitos feos",
    autor: "Boris Cyrulnik",
    genero: "Psicología",
    descripcion: "Cómo las personas pueden reconstruirse tras traumas de infancia.",
    imagen: "/imagenes/PortadaPatitos.png",
  },
  {
    titulo: "Pensar rápido, pensar despacio",
    autor: "Daniel Kahneman",
    genero: "Psicología",
    descripcion: "Cómo nuestros dos sistemas de pensamiento influyen en nuestras decisiones.",
    imagen: "/imagenes/PortadaPensar.jpeg",
  },
  {
    titulo: "Ansiedad",
    autor: "Scott Stossel",
    genero: "Psicología",
    descripcion: "Relato personal sobre los efectos y tratamientos de la ansiedad.",
    imagen: "/imagenes/PortadaAnsiedad.jpeg",
  },
  {
    titulo: "El demonio de la depresión",
    autor: "Andrew Solomon",
    genero: "Psicología",
    descripcion: "Testimonio profundo sobre la depresión.",
    imagen: "/imagenes/PortadaDemonio.jpeg",
  },

  // TERROR
  {
    titulo: "El instituto",
    autor: "Stephen King",
    genero: "Terror",
    descripcion: "Niños con poderes especiales son secuestrados y llevados a un instituto siniestro.",
    imagen: "/imagenes/PortadaInstituto.jpeg",
  },
  {
    titulo: "La Casa de los Espíritus",
    autor: "Isabel Allende",
    genero: "Terror",
    descripcion: "Realismo mágico con pasajes inquietantes sobre fantasmas y secretos familiares.",
    imagen: "/imagenes/PortadaEspiritus.jpeg",
  },
  {
    titulo: "El silencio de los corderos",
    autor: "Thomas Harris",
    genero: "Terror",
    descripcion: "Thriller psicológico con Hannibal Lecter.",
    imagen: "/imagenes/PortadaSilencio.jpeg",
  },
  {
    titulo: "Mexican Gothic",
    autor: "Silvia Moreno-Garcia",
    genero: "Terror",
    descripcion: "Casa misteriosa y secretos oscuros en México.",
    imagen: "/imagenes/PortadaMexican.jpeg",
  },
  {
    titulo: "Bird Box",
    autor: "Josh Malerman",
    genero: "Terror",
    descripcion: "Un mundo postapocalíptico donde lo que no ves puede matarte.",
    imagen: "/imagenes/PortadaBird.jpeg",
  },
  {
    titulo: "Cuento de hadas",
    autor: "Stephen King",
    genero: "Terror",
    descripcion: "Un adolescente hereda una llave a otro mundo.",
    imagen: "/imagenes/PortadaHadas.jpeg",
  },

  // CIENCIA FICCIÓN
  {
    titulo: "El problema de los 3 cuerpos",
    autor: "Cixin Liu",
    genero: "Ciencia Ficción",
    descripcion: "Durante la Revolución Cultural China, contacto con civilización alienígena.",
    imagen: "/imagenes/Portada3Cuerpos.jpeg",
  },
  {
    titulo: "Neuromante",
    autor: "William Gibson",
    genero: "Ciencia Ficción",
    descripcion: "Un hacker caído en desgracia recibe un último trabajo peligroso.",
    imagen: "/imagenes/PortadaNeuromante.jpeg",
  },
  {
    titulo: "El fin de la eternidad",
    autor: "Isaac Asimov",
    genero: "Ciencia Ficción",
    descripcion: "Un agente temporal viaja en el tiempo para modificar eventos.",
    imagen: "/imagenes/PortadaEternidad.jpeg",
  },
  {
    titulo: "La chica mecánica",
    autor: "Paolo Bacigalupi",
    genero: "Ciencia Ficción",
    descripcion: "Biotecnología y crisis ecológica en un futuro distópico.",
    imagen: "/imagenes/PortadaMecanica.jpeg",
  },
  {
    titulo: "El archivo de las tormentas",
    autor: "Brandon Sanderson",
    genero: "Ciencia Ficción",
    descripcion: "Tecnología ancestral y poderes sorprendentes en un mundo épico.",
    imagen: "/imagenes/PortadaTormentas.jpeg",
  },
  {
    titulo: "Klara y el Sol",
    autor: "Kazuo Ishiguro",
    genero: "Ciencia Ficción",
    descripcion: "Klara es una amiga artificial que descubre los matices del amor y la humanidad.",
    imagen: "/imagenes/PortadaKlara.jpeg",
  },
];
